using LibSystem.Domain.Entities.Borrowing;
using LibSystem.Domain.Entities.Members;
using LibSystem.Domain.ValueObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LibSystem.Persistence.Configurations
{
    public class MemberConfiguration : IEntityTypeConfiguration<Member>
    {
        public void Configure(EntityTypeBuilder<Member> builder)
        {
            builder.ToTable("Members");

            // PRIMARY KEY: Use base entity Id (hidden from domain)
            builder.HasKey(m => m.Id);
            builder.Property(m => m.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("Id");

            // DOMAIN ID: Map to separate column, sync with base Id
            builder.Property(m => m.MemberId)
                .HasConversion(
                    memberId => memberId.Value,
                    value => value > 0 ? MemberId.Create(value) : MemberId.Create(1))
                .HasColumnName("MemberId") // Separate column
                .ValueGeneratedNever(); // Not auto-generated by DB, but manually set in code

            // Configure a database trigger to sync MemberId with Id after insert
            // This ensures MemberId = Id for every record
            builder.Property(m => m.MemberId)
                .Metadata.SetAfterSaveBehavior(Microsoft.EntityFrameworkCore.Metadata.PropertySaveBehavior.Save);

            // Name value object
            builder.Property(m => m.Name)
                .HasConversion(
                    name => name.Value,
                    value => Domain.ValueObjects.Name.Create(value))
                .HasColumnName("Name")
                .HasMaxLength(100)
                .IsRequired();

            // BorrowedBooksCount
            builder.Property(m => m.BorrowedBooksCount)
                .HasColumnName("BorrowedBooksCount")
                .HasDefaultValue(0)
                .IsRequired();

            // Configure inheritance
            builder.HasDiscriminator<string>("MemberType")
                .HasValue<RegularMember>("RegularMember")
                .HasValue<MinorStaff>("MinorStaff")
                .HasValue<ManagementStaff>("ManagementStaff");

            builder.Property("MemberType")
                .HasMaxLength(20)
                .IsRequired();

            // Indexes
            builder.HasIndex(m => m.Name)
                .HasDatabaseName("IX_Members_Name");

            builder.HasIndex("MemberType")
                .HasDatabaseName("IX_Members_MemberType");

            builder.HasIndex(m => m.BorrowedBooksCount)
                .HasDatabaseName("IX_Members_BorrowedBooksCount");

            builder.HasIndex(m => m.MemberId)
                .IsUnique()
                .HasDatabaseName("IX_Members_MemberId");

            // Check constraints
            builder.ToTable("Members", tb =>
            {
                tb.HasCheckConstraint("CK_Members_BorrowedBooksCount",
                    $"[BorrowedBooksCount] >= 0 AND [BorrowedBooksCount] <= {Member.MAX_BORROWED_BOOKS}");

                tb.HasCheckConstraint("CK_Members_MemberType",
                    "[MemberType] IN ('RegularMember', 'MinorStaff', 'ManagementStaff')");
            });

            // Audit fields
            builder.Property(m => m.CreatedAt)
                .IsRequired()
                .HasDefaultValueSql("GETUTCDATE()");

            builder.Property(m => m.UpdatedAt)
                .IsRequired()
                .HasDefaultValueSql("GETUTCDATE()");

            builder.Ignore(m => m.DomainEvents);
        }
    }
}
