// <auto-generated />
using System;
using LibSystem.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibSystem.Persistence.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibSystem.Domain.Entities.Books.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Author");

                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("BookId");

                    b.Property<int>("Category")
                        .HasColumnType("int")
                        .HasColumnName("Category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsAvailable");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int")
                        .HasColumnName("PublicationYear");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Author")
                        .HasDatabaseName("IX_Books_Author");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_Books_Category");

                    b.HasIndex("IsAvailable")
                        .HasDatabaseName("IX_Books_IsAvailable");

                    b.HasIndex("Title", "PublicationYear")
                        .IsUnique()
                        .HasDatabaseName("UQ_Books_Title_Year");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "F. Scott Fitzgerald",
                            BookId = 1,
                            Category = 0,
                            CreatedAt = new DateTime(2025, 6, 26, 8, 49, 33, 55, DateTimeKind.Utc).AddTicks(4948),
                            IsAvailable = true,
                            PublicationYear = 1925,
                            Title = "The Great Gatsby",
                            UpdatedAt = new DateTime(2025, 6, 26, 8, 49, 33, 55, DateTimeKind.Utc).AddTicks(4950)
                        },
                        new
                        {
                            Id = 2,
                            Author = "Harper Lee",
                            BookId = 2,
                            Category = 0,
                            CreatedAt = new DateTime(2025, 6, 26, 8, 49, 33, 55, DateTimeKind.Utc).AddTicks(6109),
                            IsAvailable = true,
                            PublicationYear = 1960,
                            Title = "To Kill a Mockingbird",
                            UpdatedAt = new DateTime(2025, 6, 26, 8, 49, 33, 55, DateTimeKind.Utc).AddTicks(6110)
                        },
                        new
                        {
                            Id = 3,
                            Author = "George Orwell",
                            BookId = 3,
                            Category = 0,
                            CreatedAt = new DateTime(2025, 6, 26, 8, 49, 33, 55, DateTimeKind.Utc).AddTicks(6114),
                            IsAvailable = true,
                            PublicationYear = 1949,
                            Title = "1984",
                            UpdatedAt = new DateTime(2025, 6, 26, 8, 49, 33, 55, DateTimeKind.Utc).AddTicks(6115)
                        },
                        new
                        {
                            Id = 4,
                            Author = "Stephen Hawking",
                            BookId = 4,
                            Category = 1,
                            CreatedAt = new DateTime(2025, 6, 26, 8, 49, 33, 55, DateTimeKind.Utc).AddTicks(6117),
                            IsAvailable = true,
                            PublicationYear = 1988,
                            Title = "A Brief History of Time",
                            UpdatedAt = new DateTime(2025, 6, 26, 8, 49, 33, 55, DateTimeKind.Utc).AddTicks(6117)
                        },
                        new
                        {
                            Id = 5,
                            Author = "Eric Carle",
                            BookId = 5,
                            Category = 2,
                            CreatedAt = new DateTime(2025, 6, 26, 8, 49, 33, 55, DateTimeKind.Utc).AddTicks(6119),
                            IsAvailable = true,
                            PublicationYear = 1969,
                            Title = "The Very Hungry Caterpillar",
                            UpdatedAt = new DateTime(2025, 6, 26, 8, 49, 33, 55, DateTimeKind.Utc).AddTicks(6120)
                        });
                });

            modelBuilder.Entity("LibSystem.Domain.Entities.Borrowing.BorrowingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("BookId");

                    b.Property<DateTime>("BorrowedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("BorrowedAt");

                    b.Property<int>("BorrowingId")
                        .HasColumnType("int")
                        .HasColumnName("BorrowingId");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("MemberId");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ReturnedAt");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .HasDatabaseName("IX_BorrowingRecords_BookId");

                    b.HasIndex("BorrowedAt")
                        .HasDatabaseName("IX_BorrowingRecords_BorrowedAt");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("IX_BorrowingRecords_MemberId");

                    b.HasIndex("ReturnedAt")
                        .HasDatabaseName("IX_BorrowingRecords_ReturnedAt");

                    b.HasIndex("BookId", "MemberId")
                        .IsUnique()
                        .HasDatabaseName("UQ_BorrowingRecords_Active")
                        .HasFilter("[ReturnedAt] IS NULL");

                    b.HasIndex("BorrowedAt", "ReturnedAt")
                        .HasDatabaseName("IX_BorrowingRecords_Duration");

                    b.HasIndex("BookId", "MemberId", "ReturnedAt")
                        .HasDatabaseName("IX_BorrowingRecords_Active");

                    b.ToTable("BorrowingRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_BorrowingRecords_BorrowedAt", "[BorrowedAt] <= GETUTCDATE()");

                            t.HasCheckConstraint("CK_BorrowingRecords_ReturnedAt", "[ReturnedAt] IS NULL OR [ReturnedAt] >= [BorrowedAt]");
                        });
                });

            modelBuilder.Entity("LibSystem.Domain.Entities.Members.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BorrowedBooksCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("BorrowedBooksCount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("MemberId");

                    b.Property<string>("MemberType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("BorrowedBooksCount")
                        .HasDatabaseName("IX_Members_BorrowedBooksCount");

                    b.HasIndex("MemberType")
                        .HasDatabaseName("IX_Members_MemberType");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Members_Name");

                    b.ToTable("Members", null, t =>
                        {
                            t.HasCheckConstraint("CK_Members_BorrowedBooksCount", "[BorrowedBooksCount] >= 0 AND [BorrowedBooksCount] <= 5");

                            t.HasCheckConstraint("CK_Members_MemberType", "[MemberType] IN ('RegularMember', 'MinorStaff', 'ManagementStaff')");
                        });

                    b.HasDiscriminator<string>("MemberType").HasValue("Member");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LibSystem.Domain.Entities.Members.ManagementStaff", b =>
                {
                    b.HasBaseType("LibSystem.Domain.Entities.Members.Member");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Members_BorrowedBooksCount", "[BorrowedBooksCount] >= 0 AND [BorrowedBooksCount] <= 5");

                            t.HasCheckConstraint("CK_Members_MemberType", "[MemberType] IN ('RegularMember', 'MinorStaff', 'ManagementStaff')");
                        });

                    b.HasDiscriminator().HasValue("ManagementStaff");
                });

            modelBuilder.Entity("LibSystem.Domain.Entities.Members.MinorStaff", b =>
                {
                    b.HasBaseType("LibSystem.Domain.Entities.Members.Member");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Members_BorrowedBooksCount", "[BorrowedBooksCount] >= 0 AND [BorrowedBooksCount] <= 5");

                            t.HasCheckConstraint("CK_Members_MemberType", "[MemberType] IN ('RegularMember', 'MinorStaff', 'ManagementStaff')");
                        });

                    b.HasDiscriminator().HasValue("MinorStaff");
                });

            modelBuilder.Entity("LibSystem.Domain.Entities.Members.RegularMember", b =>
                {
                    b.HasBaseType("LibSystem.Domain.Entities.Members.Member");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Members_BorrowedBooksCount", "[BorrowedBooksCount] >= 0 AND [BorrowedBooksCount] <= 5");

                            t.HasCheckConstraint("CK_Members_MemberType", "[MemberType] IN ('RegularMember', 'MinorStaff', 'ManagementStaff')");
                        });

                    b.HasDiscriminator().HasValue("RegularMember");
                });
#pragma warning restore 612, 618
        }
    }
}
