<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="9.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="9.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="9.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="9.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Domain\LibSystem.Domain\LibSystem.Domain.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Identity\LibSystem.Identity\LibSystem.Indentity\LibSystem.Indentity.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Persistence\LibSystem.Persistence\LibSystem.Persistence.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Utils\LibSystem.Utils\LibSystem.Utils.csproj" />
  </ItemGroup>

</Project>
